version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bot_cs_mix
      POSTGRES_USER: wesley
      POSTGRES_PASSWORD: botcsmix
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
